// <auto-generated />
using System;
using Meetup.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Meetup.Entities.Migrations
{
    [DbContext(typeof(MeetupDbContext))]
    [Migration("20201213191429_AddMeetupFeedback")]
    partial class AddMeetupFeedback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Meetup.Entities.Models.Meetup", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("ParticipantsCount");

                    b.Property<string>("Topic")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Meetup");
                });

            modelBuilder.Entity("Meetup.Entities.Models.MeetupDetail", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("ParticipantsCount");

                    b.Property<string>("Topic")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("MeetupDetail");
                });

            modelBuilder.Entity("Meetup.Entities.Models.MeetupFeedback", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Category");

                    b.Property<string>("Feedback");

                    b.Property<int>("FeedbackIndex");

                    b.HasKey("Id");

                    b.ToTable("MeetupFeedback");
                });
#pragma warning restore 612, 618
        }
    }
}
